server-port: 80

mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: yggdrasil

redis:
  host: localhost
  port: 6379
  password: root
  database: 1

privateKey:
publicKey:

server-info:
  serverName: 积木brick-Yggdrasil验证端
  maxTimes: 5